name: Azure Web App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip deployment package
        run: |
          cd bytebouncer
          zip -r ../deploy.zip .
          cd ..
          zip -g deploy.zip requirements.txt startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: bytebouncerapp
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy.zip

      - name: Set startup command
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp config set --resource-group myResourceGroup --name bytebouncerapp --startup-file "startup.sh"
